name: ping endpoint
on:
  schedule:               #TIMES IN CENTRAL TIME
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: curl endpoint
        run: |
            curl -X HEAD https://agent-smark-backend.vercel.app/ping